# This is a YAML document
---
# Define the build configuration
build:
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
  ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"

# Define the archive configuration
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# Define the checksum configuration
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

# Define the signing configuration
signs:
  - cmd: gpg --output "${signature}" --detach-sign "${artifact}"
    artifacts:
      - checksum

# Define the release configuration
release:
  github:
    owner: your-github-username
    name: your-github-repo-name
  draft: false
  prerelease: false
  body: "Release {{ .Version }}"

# Define the hooks configuration
hooks:
  # Run 'go mod tidy' before building
  pre:
    - go mod tidy