# This is a YAML document
---
# Define the build configuration
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"

# Define the archive configuration
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip

# Define the checksum configuration
checksum:
  algorithm: sha256

# Define the signing configuration
signs:
  - artifacts:
      - checksum
    cmd: gpg --output "${signature}" --detach-sign "${artifact}"

# Define the release configuration
release:
  draft: false
  github:
    owner: your-github-username
    name: your-github-repo-name
  body: "Release {{ .Version }}"
  prerelease: false

# Define the hooks configuration
hooks:
  pre:
    - go mod tidy